[[IgnoredVulns]]
id = "RUSTSEC-2021-0141"
reason = "The crate is unmaintained, but it works. If there is any new vulnerability, there will be another ID."

[[IgnoredVulns]]
id = "RUSTSEC-2024-0384"
reason = "The crate is unmaintained, but it works. If there is any new vulnerability, there will be another ID."

[[IgnoredVulns]]
id = "RUSTSEC-2024-0388"
reason = "The crate is unmaintained, but it works. If there is any new vulnerability, there will be another ID."

[[IgnoredVulns]]
id = "RUSTSEC-2024-0436"
reason = "The crate is unmaintained, but it works. If there is any new vulnerability, there will be another ID."
